=== Lanz86/open_municipio/docs/dev/data_import/OpenMunicipioDataImport.xsd
<?xml version="1.0" encoding="UTF-8"?>
	<xs:schema
		xmlns:xs="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.w3schools.com"
		xmlns="http://www.w3schools.com"
		elementFormDefault="qualified">
	
<!-- BEGIN auxiliary types -->	
	<xs:complexType name="actType" >
		<xs:sequence>
		<!-- 
			<xs:element ref="PresentingInstitutions" minOccurs="1" maxOccurs="1" />
			<xs:element ref="TargetInstitutions" minOccurs="0" maxOccurs="1" />  -->
<!-- 		use specialized step informations			
	<xs:element ref="TransitionStep" minOccurs="1" maxOccurs="unbounded" /> -->
			<xs:element ref="Section" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:string" />
		<xs:attribute name="title" use="required" type="xs:string" />
		<xs:attribute name="adj_title" use="optional" type="xs:string" />
		<xs:attribute name="expire_date" use="optional" type="dateType" />
		<!-- presentation date is not present because every it is derived from the first TransitionStep -->
		<!-- the text of the act must be wrapped in a Section -->
	</xs:complexType>
	
	<xs:complexType name="councilActType">
		<xs:complexContent>
			<xs:extension base="actType">
				<xs:sequence>
					<xs:element ref="ActSubscribers" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
				<!-- TODO What is this site about?!? -FS  -->
				<xs:attribute name="site" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="commission" />
							<xs:enumeration value="council" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- a deliberation can be subscribed by institutions (I presume also by citizens. Check it! -FS) -->
	<xs:element name="ActSubscribers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Institution" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- unused at the moment -->
	<xs:element name="ActTargets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Institution" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:complexType name="bodyType" >
		<xs:sequence>
			<xs:element ref="Charge" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="description" type="xs:string" use="optional" />
	</xs:complexType>
		
	<xs:simpleType name="genderType" >
		<xs:restriction base="xs:token">
			<xs:enumeration value="m"/>
			<xs:enumeration value="f"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="ssnType" >
		<xs:restriction base="xs:string">
			<xs:length value="16" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="dateType">
		<xs:union memberTypes="xs:dateTime">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="unknown" />
				</xs:restriction>			
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	
	<xs:simpleType name="chargeType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Administration" />
			<xs:enumeration value="Company" />
			<xs:enumeration value="Institution" />
		</xs:restriction>
	</xs:simpleType>
<!-- END auxiliary types -->	

<!-- ROOT -->
	<xs:element name="OpenMunicipio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Bodies" minOccurs="0" maxOccurs="1" />
				<xs:element ref="Acts" minOccurs="0" maxOccurs="1" />
				<xs:element ref="Ballot" minOccurs="0" maxOccurs="1" />
				<xs:element ref="Groups" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>	

	
<!-- BEGIN groups and people -->	
	
	<xs:element name="Persons">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Person" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Person">
		<xs:complexType>		
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="last_name" use="required" type="xs:string" />
			<xs:attribute name="birth_date" type="xs:date" use="optional" />
			<xs:attribute name="birth_place" type="xs:string" use="optional" />
			<xs:attribute name="sex" type="genderType" use="optional" />
			<xs:attribute name="ssn" type="ssnType" use="optional" />
			
		</xs:complexType>
	</xs:element>
		
	<xs:element name="Groups">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Group" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Group">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Person" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="acronym" type="xs:string" />
		</xs:complexType>
	</xs:element>

<!-- BEGIN bodies -->	
	<xs:element name="Bodies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Offices" minOccurs="0" maxOccurs="1" />
				<xs:element ref="Companies" minOccurs="0" maxOccurs="1" />
				<xs:element ref="Institutions" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Offices" >
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Office" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		
		<!-- perche` non funziona con xpath="./Office/ -->
		<xs:key name="officeHasUniqueName">
			<xs:selector xpath="./*" />
			<xs:field xpath="@name" />
		</xs:key>
	</xs:element>
	
	<xs:element name="Office" type="bodyType" />
	
	<xs:element name="Charge">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Person" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="start_date" type="dateType" use="required" />
			<xs:attribute name="end_date" type="dateType" use="optional" />
			<xs:attribute name="end_reason" type="xs:string" use="optional" />
			<xs:attribute name="description" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="Companies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Company" minOccurs="0" maxOccurs="unbounded"  />
			</xs:sequence>
		</xs:complexType>	
	</xs:element>
	
	<xs:element name="Institutions" >
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Institution" minOccurs="0" maxOccurs="unbounded"  />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Company" type="bodyType" />
	<xs:element name="Institution" type="bodyType" />
<!-- END bodies -->

<!-- BEGIN acts -->	
	<xs:element name="Acts">
		<xs:complexType>
			<xs:sequence>
				<!-- Acts of the City Council -->
				<xs:element ref="ActsCouncil" minOccurs="0" maxOccurs="1"/>
				<!-- Acts of the Giunta Municipale. Apparently both Consiglio Comunale and Giunta Municipale translate to City Council -->
				<xs:element ref="ActsGiunta" minOccurs="0" maxOccurs="1"/>
				<!-- Acts of the City Mayor -->
				<xs:element ref="ActsMayor" minOccurs="0" maxOccurs="1"/>
				<!-- Administrative acts of the various offices -->
				<xs:element ref="ActsOffices" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>

		<!-- I expect the selector xpath to be '*/Section' but it does not work in that way -->
		<xs:unique name="actHasUniqueId">
 			<xs:selector xpath="./*/*" /> <!-- only Section's of level 2 --> 
			<xs:field xpath="@title" />
		</xs:unique>
	</xs:element>
	
	<xs:element name="ActsCouncil">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Interrogation" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Interpellation" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Motion" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Agenda" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="Emendation" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="CouncilDeliberation" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ActsGiunta" />
	
	<xs:element name="ActsMayor" />
	
	<xs:element name="ActsOffices" />
		
	<xs:element name="Interrogation" >
		<xs:complexType >
			<xs:complexContent >
				<xs:extension base="actType"  >
					<xs:sequence>
						<xs:element ref="ActTargets" minOccurs="1" maxOccurs="1" />
						<xs:element ref="QuestionText" minOccurs="1" maxOccurs="1" />
						<!-- the Answer is optional because the act may have not received it, yet -->
						<xs:element ref="Answer" minOccurs="0" maxOccurs="1" />
						<xs:element ref="InterrogationStep" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="answer_type" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<xs:enumeration value="written" />
								<xs:enumeration value="oral" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="QuestionText" >
		<xs:complexType mixed="true" />
	</xs:element>
	
	<xs:element name="Answer" >
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ReplyInstitution" />
				<xs:element ref="ReplyText" />
			</xs:sequence>
			<xs:attribute name="answerType" use="required"  >
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="written" />
						<xs:enumeration value="oral" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="site" use="required"  >
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="council" />
						<xs:enumeration value="commission" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ReplyText" />
	<xs:element name="ReplyInstitution" type="bodyType">
		
	</xs:element>
	
	<xs:element name="Interpellation">
		<xs:complexType >
			<xs:complexContent >
				<xs:extension base="councilActType"  >
					<xs:sequence>
						<xs:element ref="ActTargets" minOccurs="1" maxOccurs="1" />
						<xs:element ref="QuestionText" minOccurs="1" maxOccurs="1" />
						<!-- the Answer is optional because the act may have not received it, yet -->
						<xs:element ref="Answer" minOccurs="0" maxOccurs="1" />
						<xs:element ref="Interpellation" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Agenda">	
		<xs:complexType>
			<xs:complexContent >
				<xs:extension base="councilActType"  >
					<xs:sequence>
						<xs:element ref="Emendation" minOccurs="0" maxOccurs="unbounded" />
						<xs:element ref="Ballot" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>			
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Motion" type="actType" >
				<xs:complexType>
			<xs:complexContent >
				<xs:extension base="councilActType"  >
					<xs:sequence>
						<xs:element ref="Emendation" minOccurs="0" maxOccurs="unbounded" />
						<xs:element ref="Ballot" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>			
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="Emendation">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="actType" >
					<xs:attribute name="act" type="xs:string" use="required" />
					<xs:attribute name="section" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
		
		
	</xs:element>
	
	<xs:element name="TransitionStep">
		<xs:complexType>
			<xs:attribute name="name">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<!-- generic -->
						<xs:enumeration value="Presented" />
						<xs:enumeration value="Voted" />
						<!-- Aggiungere gli stati del workflow di presentazione degli atti -->
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="date" type="dateType" />
			<!-- a concise description of the reason that lead the transition to this step -->
			<xs:attribute name="reason" type="xs:string" />
			<!-- in the note field it is possible to store unstructure information attached to the transition -->
			<xs:attribute name="note" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="InterrogationStep">
		<xs:complexType>
			<xs:attribute name="name">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<!-- generic -->
						<xs:enumeration value="Presented" />
						<xs:enumeration value="Answered" />
						<xs:enumeration value="Decayed" />
						<xs:enumeration value="Retired" />
						<xs:enumeration value="Postponed" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="date" type="dateType" />
			<!-- a concise description of the reason that lead the transition to this step -->
			<xs:attribute name="reason" type="xs:string" />
			<!-- in the note field it is possible to store unstructure information attached to the transition -->
			<xs:attribute name="note" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="InterpellationStep">
		<xs:complexType>
			<xs:attribute name="name">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<!-- generic -->
						<xs:enumeration value="Presented" />
						<xs:enumeration value="Answered" />
						<xs:enumeration value="Decayed" />
						<xs:enumeration value="Retired" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="date" type="dateType" />
			<!-- a concise description of the reason that lead the transition to this step -->
			<xs:attribute name="reason" type="xs:string" />
			<!-- in the note field it is possible to store unstructure information attached to the transition -->
			<xs:attribute name="note" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="AgendaStep">
		<xs:complexType>
			<xs:attribute name="name">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<!-- generic -->
						<xs:enumeration value="Presented" />
						<xs:enumeration value="Accepted" />
						<xs:enumeration value="Decayed" />
						<xs:enumeration value="Retired" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="date" type="dateType" />
			<!-- a concise description of the reason that lead the transition to this step -->
			<xs:attribute name="reason" type="xs:string" />
			<!-- in the note field it is possible to store unstructure information attached to the transition -->
			<xs:attribute name="note" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Section" >
		<xs:complexType >
			<xs:sequence>
				<xs:element ref="SectionText" />
				<xs:element ref="Section" minOccurs="0" maxOccurs="unbounded" />				
			</xs:sequence>
			<xs:attribute name="title" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="SectionText">
		<xs:complexType mixed="true" />
	</xs:element>
		
	<xs:element name="CouncilDeliberation">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="actType" >
					<xs:sequence>
						<xs:element ref="ActSubscribers" />
					</xs:sequence>
					<xs:attribute name="approval_date" type="xs:date" use="required" />
					<!-- publication_date is the same as presentation_date, see actType -->
					<xs:attribute name="execution_date" type="xs:date" use="required" />
					<xs:attribute name="initiative" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<!-- The initiative came from the Council -->
								<xs:enumeration value="council_member" />
								<xs:enumeration value="council_president" />
								<!-- The initiative came from the Giunta -->
								<xs:enumeration value="alderman" />
								<xs:enumeration value="mayor" />
								<xs:enumeration value="giunta" />
								<!-- The initiative came from the Citizens -->
								<xs:enumeration value="citizens" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
<!-- END acts -->
	
<!-- BEGIN ballots and votes -->	
	<xs:element name="Ballot" />
	
<!-- END ballots and votes -->	
</xs:schema>

=== Lanz86/open_municipio/docs/dev/data_import/exampleActs.xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenMunicipio
	xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com OpenMunicipioDataImport.xsd"
	xmlns:xi="http://www.w3.org/2001/XInclude">
	<Acts>
		<Motion id="M.123.a" title="This is a very important motion" >
			<PresentingInstitution>
				<Institution name="Assessorato dell'universo">
					<Charge start_date="2011-01-01">
						<Person ssn="1112223334445556" last_name="AAAA" name="BBBB" />
					</Charge>
				</Institution>
			</PresentingInstitution>
			<ProcessStep name="Presented" date="2012-01-01T00:00:00" />
			<Section title="M.123.a-Introduction" >
				<SectionText>
					This is the first and most important part of this motion
				</SectionText>
			</Section>
			<Section title="M.123.a-Chapter1" >
				<SectionText>
				This is a not so important chapter
				</SectionText>
			</Section>
			<Section title="M.123.a-Chapter2" >
				<SectionText>
				Try a duplicate chapter name
				</SectionText>
				<Section title="M.123.a-Chapter2" >
					<SectionText>
					Try a duplicate chapter name
					</SectionText>
				</Section>
			</Section>
		</Motion>
		<Motion id="M.123.b" title="This is a very important motion2" >
			<PresentingInstitutions>
				<Institution name="Assessore allo Sport" description="E` quello che si occupa di assessorare lo sport">
					<Charge  start_date="2011-01-01T00:00:00" end_date="2011-12-31T00:00:00">
						<Person ssn="1231231231231234" last_name="Foo" name="Fie" birth_date="2008-01-01" sex="m" birth_place="Senigallia (AN)"/>
					</Charge>
				</Institution>
				<Institution name="Assessore allo Sport" description="E` quello che si occupa di assessorare lo sport">
					<Charge  start_date="2011-01-01T00:00:00" end_date="2011-12-31T00:00:00">
						<Person ssn="1231231231231234" last_name="Foo" name="Fie" birth_date="2008-01-01" sex="m" birth_place="Senigallia (AN)"/>
					</Charge>
				</Institution>
			</PresentingInstitutions>
			<ProcessStep name="Presented" date="2012-01-01T00:00:00" />
			<ProcessStep name="Voted" date="2012-01-02T00:00:00" />
			<Section title="M.123.b-Introduction" > 
				<SectionText>
					This is the first and most important part of this motion
				</SectionText>
			</Section>
			<Section title="M.123.b-Chapter1" >
				<SectionText>
					This is a not so important chapter
				</SectionText>
			</Section>
			<Section title="M.123.b-Chapter2" >
				<SectionText>
					Try a duplicate chapter name
				</SectionText>
			</Section>
		</Motion>
		
	</Acts>
</OpenMunicipio>

=== Lanz86/open_municipio/import_tmp/docs/examplePersons.xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenMunicipio
	xmlns="http://www.w3schools.com"	
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com OpenMunicipioDataImport.xsd"
	xmlns:xi="http://www.w3.org/2001/XInclude">
	<Groups>
		<Group name="Partito dell'Amore" acronym="PdA">
			<Person
				name="Pippo"
				last_name="Poppi"
				birth_date="1982-07-26"
				birth_place="Loreto (AN)"
				sex="m"
				ssn="PPPPPP86L26E690K" />
			<Person
				name="AAAA"
				last_name="BBBB"
				birth_date="1982-07-26"
				birth_place="Loreto (AN)"
				sex="f"
				ssn="AAABBB86L26E690K" />
			<Person
				name="XXXX"
				last_name="YYYY"
				birth_date="1982-07-26"
				birth_place="Loreto (AN)"
				sex="f"
				ssn="XXXYYY86L26E690K" />
		</Group>
		<Group name="Partito dell'Odio" acronym="PdO">
			<Person
				name="Paperino"
				last_name="Paolino"
				birth_date="1982-07-26"
				birth_place="Loreto (AN)"
				sex="m"
				ssn="PPPPPP86L26E690K" />
			<Person
				name="Gino"
				last_name="Lollobriggido"
				birth_date="1982-07-26"
				birth_place="Loreto (AN)"
				sex="f"
				ssn="AAABBB86L26E690K" />
			<Person
				name="Mister"
				last_name="Muscolo"
				birth_date="1982-07-26"
				birth_place="Loreto (AN)"
				sex="f"
				ssn="XXXYYY86L26E690K" />
			
		</Group>
	</Groups>
</OpenMunicipio>

=== Lanz86/open_municipio/docs/dev/data_import/people_sample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenMunicipio
	xmlns="http://www.openmunicipio.it"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openmunicipio.it OpenMunicipioDataImport.xsd">
	<People>
		<Offices>
			<Office name="Ufficio Anagrafe" description="Elenco degli abitanti del comune">
				<Charge id="pippo_poppi" start_date="2012-01-01T00:00:00" end_date="2012-01-02T00:00:00" end_reason="too lazy" description="dipendente" >
					<Person ssn="BBBCCC00L26AASD1" last_name="Poppi" first_name="Pippo" birth_date="2000-07-26" sex="m" birth_place="Topolinia (TP)"/>
				</Charge>
				<Charge id="topolino_topoloni" start_date="2012-01-01T00:00:00" end_date="2012-01-02T00:00:00" end_reason="too lazy" description="dirigente" >
					<Person ssn="BBBCCC00L26AASD1" last_name="Topolino" first_name="Topoloni" birth_date="2000-07-26" sex="m" birth_place="Topolinia (TP)"/>
				</Charge>
			</Office>
			<Office name="Un altro ufficio" description="Elenco degli abitanti del comune">
				<Charge id="poppi_" start_date="2012-01-01T00:00:00" end_date="2012-01-02T00:00:00" end_reason="too lazy" description="dipendente" >
					<Person ssn="BBBCCC00L26AASD1" last_name="Poppi" first_name="Pippo" birth_date="2000-07-26" sex="m" birth_place="Topolinia (TP)"/>
				</Charge>
				<Charge id="topolini_topolino" start_date="2012-01-01T00:00:00" end_date="2012-01-02T00:00:00" end_reason="too lazy" description="dirigente" >
					<Person ssn="BBBCCC00L26AASD1" last_name="Topolino" first_name="Topoloni" birth_date="2000-07-26" sex="m" birth_place="Topolinia (TP)"/>
				</Charge>
			</Office>
		</Offices>
	</People>
</OpenMunicipio>
